### ISSUE TITLE
Info - Error timeout

### ISSUE THREAD

**Issue by heavymanto** [JKorf/CoinGecko.Net#1]
**Describe the bug**
hello, unfortunately I often receive knockouts due to timeouts even on single calls made several minutes apart. Reading in the various forums I saw that there are some options to lengthen the time out but I don't understand how to set them. Can you give me an example? timeouts: 10000,
   autoRetry: true,

example
https://www.npmjs.com/package/coingecko-api-v3

Thanks very much for your work.

**Comment by JKorf** [comment]
Hi, request timeout can be set in the client options, for example:
````csharp
var coinGecko = new CoinGeckoClient(new CoinGeckoClientOptions
{
    ApiOptions = new RestApiClientOptions
    {
        RequestTimeout = TimeSpan.FromSeconds(60)
    }
});
````

There is no automatic retry build into the library, however you can provide your own HttpClient instance and can use for example Polly to set a retry policy on that client if I remember correctly.

**Comment by heavymanto** [comment]
thanks you
