### ISSUE TITLE
ApiCredentials and PRO endpoints

### ISSUE THREAD

**Issue by masherak** [JKorf/CoinGecko.Net#12]
Hello,

I have two problems...

1)  I’m trying to define ApiCredentials with an ApiKey(should be in request header), but it’s not working because there is no secret for CoinGecko (only an ApiKey), and I’m getting an error saying 'secret cannot be null'. 
--- I can implement method "IServiceCollection AddCoinGecko" again with modified http client default headers, but is it right way?

2) How can I switch to the PRO endpoints? I only have an ApiKey for the PRO version of the API. 
--- maybe via "CoinGeckoEnvironment CreateCustom" method? Is it right way?

3) I have also defined a rate limiter with 'Wait' settings, but it is throwing a 429 too many requests error

Thank you very much for your help.

I solved it with this method, but I think it can be useful also for others who wanna use PRO tier of API.

<img width="935" alt="image" src="https://github.com/user-attachments/assets/2e40b11b-7ecc-4f18-838b-48e412e5b6c8">

**Comment by masherak** [comment]
@JKorf  Thank you for 3.0.0 update!

**Comment by JKorf** [comment]
You're welcome! Let me know if you have any issues
