### ISSUE TITLE
Input string '8.721952937706929e+36' is not a valid decimal

### ISSUE THREAD

**Issue by kostyrin** [JKorf/CoinGecko.Net#4]
**Describe the bug**
When trying to retrieve 1000 coins with markets then get the error.
Please check API Docs https://www.coingecko.com/api/documentation?deepLinking=1#/coins/get_coins_markets
, there is precision filter. It might be helpful.

**To Reproduce**
```
var client = new CoinGeckoRestClient();
var coinsResponse = await client.Api.GetMarketsAsync("usd", pageSize: 1000);

var coinsResponse2 = await client.Api.GetMarketsAsync("usd", category: "cryptocurrency", pageSize: 100);
```

**Expected behavior**
no errors

**Debug logging**
Deserialize JsonReaderException: Input string '8.721952937706929e+36' is not a valid decimal. Path '[165].atl_change_percentage', line 1, position 132925., Path: [165].atl_change_percentage, LineNumber: 1, LinePosition: 132925

Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path '[51].high_24h', line 1, position 40595.

**Comment by kostyrin** [comment]
suggestion: rename method to GetAssetMarkets or like that..

**Comment by JKorf** [comment]
Well this is a funny one. 8.708131176238499E+36 is larger than the max value of decimal in C#, so I'm not sure how to fix that atm

**Comment by kostyrin** [comment]
@JKorf please check the api, there is precision filter. It might be helpful.
![image](https://github.com/JKorf/CoinGecko.Net/assets/8361000/76bbbcdc-8ae4-4108-932e-793ef707d3df)

**Comment by JKorf** [comment]
Doesn't seem to help unfortunately

**Comment by 0x3abc** [comment]
In my case the error was cause by the following JSON entry:
```json
{
  "atl_change_percentage": 1.3041022457098233E+37
}
```
I solved the problem by changing the property type from `decimal` to `double`:
```cs
public double AllTimeLowChangePercentage { get; set; }
```

**Comment by 0x3abc** [comment]
There can be also null values in the JSON response (for example `"high_24h": null`):
```json
{
    "id": "saitama-inu",
    "symbol": "saitama",
    "name": "Saitama",
    "image": "https://assets.coingecko.com/coins/images/16353/large/SOIKDUWf_400x400.jpeg?1696515952",
    "current_price": 0.0024117,
    "market_cap": 108037051,
    "market_cap_rank": 492,
    "fully_diluted_valuation": 108075339,
    "total_volume": 377.5,
    "high_24h": null,
    "low_24h": null,
    "price_change_24h": null,
    "price_change_percentage_24h": null,
    "market_cap_change_24h": null,
    "market_cap_change_percentage_24h": null,
    "circulating_supply": 44797105328.77,
    "total_supply": 44812981146.0,
    "max_supply": 100000000000.0,
    "ath": 0.00433786,
    "ath_change_percentage": -44.40352,
    "ath_date": "2022-07-29T23:36:40.637Z",
    "atl": 2.605E-11,
    "atl_change_percentage": 9258115776.8141,
    "atl_date": "2021-07-07T19:28:30.496Z",
    "roi": null,
    "last_updated": "2024-03-07T18:30:08.505Z"
  }
```

**Comment by JKorf** [comment]
I've updated the model to reflect the nullable properties and changed the percentage fields to double type. Let me know if there are any issues

**Comment by chrisjainsley** [comment]
Just come across this error in the CoinGeckoMarketData class. Looks like that needs changing to a double too.

https://github.com/JKorf/CoinGecko.Net/blob/ed43df78f5193f199d70a513f1951630ed199946/CoinGecko.Net/Objects/Models/CoinGeckoMarketData.cs#L62
