### ISSUE TITLE
 GetAssetDetails - Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by kostyrin** [JKorf/CoinGecko.Net#5]
**Describe the bug**
When trying to retrieve details by some coin like `wbtc` then get the error.

**To Reproduce**
```
var client = new CoinGeckoRestClient();
var response = await client.Api.GetAssetDetailsAsync("wbtc");
```

**Expected behavior**
no errors

**Debug logging**
Deserialize JsonReaderException: Unexpected character encountered while parsing value: {. Path 'market_data.total_value_locked', line 1, position 26513., Path: market_data.total_value_locked, LineNumber: 1, LinePosition: 26513

**Comment by JKorf** [comment]
wbtc doesn't seem to be a valid value for that call, which is also what the error result is when I try it. Could you double check that?

**Comment by kostyrin** [comment]
@JKorf  the same for `matic-network`
```
Deserialize JsonReaderException: Unexpected character encountered while parsing value: {. Path 'market_data.total_value_locked', line 1, position 32663., Path: market_data.total_value_locked, LineNumber: 1, LinePosition: 32663
```
there is a lot of examples with the issue

![image](https://github.com/JKorf/CoinGecko.Net/assets/8361000/c743e590-623d-434b-a6dc-c6f3fc5a6e71)

for an instance
`bitcoin` is all right
![image](https://github.com/JKorf/CoinGecko.Net/assets/8361000/d33d9b55-acc4-4135-9015-7008bad6c2e6)

**Comment by JKorf** [comment]
I've fixed this in the latest version
